# permissions for end users to edit instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: instance-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: qdrant-operator
    app.kubernetes.io/part-of: qdrant-operator
    app.kubernetes.io/managed-by: kustomize
  name: instance-editor-role
rules:
- apiGroups:
  - qdrant.lburgazzoli.github.io
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qdrant.lburgazzoli.github.io
  resources:
  - instances/status
  verbs:
  - get
