---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: qdrant-operator-clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: qdrant-operator
    app.kubernetes.io/part-of: qdrant-operator
    app.kubernetes.io/managed-by: kustomize
  name: qdrant-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qdrant-operator
subjects:
- kind: ServiceAccount
  name: qdrant-operator
  namespace: qdrant-system