---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qdrant-operator
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qdrant.lburgazzoli.github.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qdrant.lburgazzoli.github.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - qdrant.lburgazzoli.github.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - qdrant.lburgazzoli.github.io
  resources:
  - collections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qdrant.lburgazzoli.github.io
  resources:
  - collections/finalizers
  verbs:
  - update
- apiGroups:
  - qdrant.lburgazzoli.github.io
  resources:
  - collections/status
  verbs:
  - get
  - patch
  - update
