apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: qdrant-operator
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: qdrant-operator
    app.kubernetes.io/part-of: qdrant-operator
    app.kubernetes.io/managed-by: kustomize
  name: qdrant-operator
  namespace: qdrant-system
