apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: qdrant-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/qdrantio/qdrant-operator-catalog:v0.0.5
  displayName: Kaoto Operator Catalog
  publisher: qdrant.io
  updateStrategy:
    registryPoll:
      interval: 30m

