apiVersion: qdrant.lburgazzoli.github.io/v1alph1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: instance
    app.kubernetes.io/instance: instance-sample
    app.kubernetes.io/part-of: qdrant-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: qdrant-operator
  name: instance-sample
spec:
  # TODO(user): Add fields here
